image: python

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

test:
  stage: test
  script:
    - python -V
    - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
    - source $HOME/.poetry/env && poetry install
    - poetry run pytest --cov-report term --cov=lambda_layer_whitelisting tests/
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'develop'