image: python

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

test:
  stage: test
  script:
    - python -V
    - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
    - source $HOME/.poetry/env && poetry install
    - poetry run pytest --cov-report term --cov=lambda_layer_whitelisting tests/
  rules:
    - if: $CI_MERGE_REQUEST_ID

create_badge_svg:
  stage: build
  image: python:3.6.6
  tags:
    - docker
  script:
    - echo "Python other dependencies installation"
  after_script:
    - pip install anybadge
    - commits=$(git rev-list --all --count)
    - anybadge -l commits -v $commits -f commits.svg -c green
  artifacts:
    paths:
        - commits.svg
    when: always
    expire_in: 4 weeks
